print("Let's begin the game!")

entries_1 = [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua & Barbuda',
        'Argentina',
        'Armenia',
        'Agra',
        'Ahmedabad',
        'Australia',
        'Austria',
        'Andheri',
        'Azerbaijan',
        'Amroha',
        'Amravati',
        'Agartala',
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Abu Dhabi',
        'Aizawl',
        'Andaman & Nicobar Islands',
        'Bahamas',
        'Bihar',
        'Bengaluru',
        'Bangalore',
        'Beijing',
        'Baghdad',
        'Bhopal',
        'Bhubaneshwar',
        'Bhararisen',
        'Bijnor',
        'Bangkok',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivia',
        'Bosnia Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Burkina',
        'Burundi',
        'Chhattisgarh',
        'Champaran',
        'Chandigarh',
        'Chennai',
        'Chittorgarh',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cape Verde',
        'Central African Rep',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo',
        'Congo (Democratic Rep)',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Dispur',
        'Dharamshala',
        'Daman & Diu',
        'Dadra & Nagar Haveli',
        'Delhi',
        'Dhaka',
        'Dubai',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'East Timor',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Eswatini',
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Goa',
        'Gujarat',
        'Gandhinagar',
        'Gangtok',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Grenada',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Honduras',
        'Himachal Pradhesh',
        'Haryana',
        'Hyderabad',
        'Hungary',
        'Iceland',
        'India',
        'Itanagar',
        'Imphal',
        'Islamabad',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland (Republic)',
        'Israel',
        'Italy',
        'Ivory Coast',
        'Jamaica',
        'Japan',
        'Jharkhand',
        'Jaipur',
        'Jakarta',
        'Jammu & Kashmir',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kathmandu',
        'Karnataka',
        'Kerala',
        'Kohima',
        'Kolkata',
        'Kavaratti',
        'Kiribati',
        'Kingston',
        'Kyoto',
        'Kosovo',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lucknow',
        'Lakshadweep',
        'Ladakh',
        'Leh',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macedonia',
        'Madagascar',
        'Madhya Pradesh',
        'Maharashtra',
        'Mumbai',
        'Manipur',
        'Manilla',
        'Meghalaya',
        'Mizoram',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'North Korea',
        'Nagaland',
        'Nainital',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'Norway',
        'Oman',
        'Odisha',
        'Ottawa',
        'Pakistan',
        'Palau',
        'Patna',
        'Panaji',
        'Punjab',
        'Prayagraj',        
        'Palestine',
        'Port Blair',
        'Pyongyang',
        'Puducherry',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Rwanda',
        'Rameshwaram',
        'Raipur',
        'Ranchi',
        'Rajasthan',
        'St Kitts & Nevis',
        'St Lucia',
        'Saint Vincent & the Grenadines',
        'Samoa',
        'San Marino',
        'South Korea',
        'Shimla',
        'Shillong',
        'Sikkim',
        'Srinagar',
        'Sao Tome & Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Seoul',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Sweden',
        'Switzerland',
        'Syria',
        'Taiwan',
        'Thiruvananthapuram',
        'Thimpu',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Togo',
        'Tonga',
        'Tokyo',
        'Trinidad & Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Unnao',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Vatican City',
        'Venezuela',
        'Vietnam',
        'West Bengal',
        'Xiangyang',
        'Yemen',
        'Zambia',
        'Zimbabwe'
    ]
entries_2 = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Sacramento',
    'Colorado',
    'Denver',
    'Connecticut',
    'Delaware',
    'Florida',
    'Tallahassee',
    'Georgia',
    'Atlanta',
    'Hawaii',
    'Honolulu',
    'Idaho',
    'Illinios',
    'Indiana',
    'Indianapolis',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Frankfort',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Boston',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Helena',
    'Nebraska',
    'Lincoln',
    'Neveda',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'Manhattan',
    'Brooklyn',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oklahoma City',
    'Oregon',
    'Pennsylvania',
    'Rhoda Island',
    'South Carolina',
    'South Dakoda',
    'Tennessee',
    'Nashville',
    'Texas',
    'Austin',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington DC',
    'West Virginia',
    'Wisconsin',
    'Madison',
    'Wyoming'
]
entries_1.extend(entries_2)

while True:
    a = input('Enter name here: ')
    b = a[-1]
    c = [idx for idx in entries_1 if idx[0].lower() == b.lower()]
    import random
    d = random.choice(c)
    print('You chose:', a)
    print('Computer chose:', d)